name: Build and Release VRChat WebChat

on:
  push:
    tags:
      - 'v*' # Matches all tags starting with v, e.g., v1.0, v1.1, etc.

jobs:
  build:
    runs-on: windows-latest  # Your app appears to be designed for Windows
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history and tags
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Choose appropriate Python version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Extract version from tag
      id: get_version
      run: |
        # Extract version number from tag (v1.0 -> 1.0)
        $VERSION = "${{ github.ref_name }}".Substring(1)
        echo "VERSION=$VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append
        
    - name: Build with cx_Freeze
      run: |
        python setup.py build
        
    - name: Zip build artifacts
      run: |
        $BUILD_DIR = "build/VRChat_WebChat"  # Use the build directory defined in your setup.py
        Compress-Archive -Path $BUILD_DIR/* -DestinationPath "VRChat_WebChat_${{ env.VERSION }}.zip"
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: VRChat_WebChat_${{ env.VERSION }}.zip
        name: VRChat WebChat ${{ env.VERSION }}
        draft: false
        prerelease: false
        body: |
          Automated build release version ${{ env.VERSION }}
          
          ## Installation
          1. Download and extract the zip file
          2. Run VRChat_WebChat.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
